config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"],
    message: "%{value} is not a valid size" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "%{value} is not between 0 and 5" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.button :submit, class: 'btn btn-primary w-100' %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h2>Edit your restaurant</h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All restaurants</h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li>
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
      <p><%= restaurant.address %></p>
    </li>
    <% end %>
  </ul>
  <%= link_to "Create new restaurant", new_restaurant_path, class: 'btn btn-primary' %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add your restaurant</h1>
  <%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h2><%= @restaurant.category %></h2>
<h2><%= @restaurant.phone_number %></h2>

<%= link_to 'See all restaurants', restaurants_path %>
<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
<%= link_to 'See reviews', restaurant_reviews_path(@restaurant) %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete %>

app/views/reviews/index.html.erb
<h2>Ratings for <%= @restaurant.name %></h2>

<div class= "container">
  <% @reviews.each do |review| %>
    <div class= "row">
    <h3>Rating: <%= review.rating %> </h3>
    </div>
    <div class= "row">
     <p> </p> <%= review.content %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to 'See all restaurants', restaurants_path %>
  <%= link_to 'Back to restaurant', restaurant_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<h1>Add your review</h1>
<div class= "container">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

</div>